### PR TITLE
Release/0.4.1

### PR DESCRIPTION
**Pull request by alexanderdean**

### CODE REVIEW

**Comment by ninjabear** [comment]
Hey @alexanderdean, 0.4.1 was a release candidate for isolating a problem Josh was having getting factotum to start.

It has two minor fixes in it, one is changing the `panic!` into a sensible error message if factotum cannot use the log file in `.factotum/factotum.log` (for invalid perms etc). This is the reason for the RC (confirming that this was the problem). 

The second is a minor fix to the behaviour of the `--overwrite` flag with the `dot` subcommand. It now will allow you to call `--overwrite` if the file does not exist (rather than error). I just had a few minutes and the code open to fix this one.

This isn't blocking 0.5.0, but rather these fixes should be cherry-picked into 0.5.0 when ready.

**Comment by alexanderdean** [comment]
Hmm - given we put out rcs for 0.4.1, shouldn't we formally release the 0.4.1? It feels a bit strange to have rcs for a release we are not putting out...

**Comment by ninjabear** [comment]
Sure - we can release an official 0.4.1, I'm working on it now

**Comment by alexanderdean** [comment]
Thanks @ninjabear - please re-add the relevant tickets to the 0.4.1 milestone, I think it's empty currently...

**Pull request merged**
